package Leetcode;

import java.util.*;
import java.util.stream.Collectors;

//You are given two strings s and t.
//
//String t is generated by random shuffling string s and then add one more letter at a random position.
//
//Return the letter that was added to t.
//
//
//
//Example 1:
//
//Input: s = "abcd", t = "abcde"
//Output: "e"
//Explanation: 'e' is the letter that was added.
//Example 2:
//
//Input: s = "", t = "y"
//Output: "y"
public class FindTheDifference {
    public static void main(String[] args){
       String s = "abcdef", t = "edcbafgh";
        Set<String> set = new HashSet<String>();
        //Set<Integer> set = new HashSet<Integer>(); if we store
        // string to integer we get NumberFormatException
       Arrays.stream(s.split(""))
                .forEach(i->set.add(i));
       System.out.println(set);
       Arrays.stream(t.split(""))
               .filter(i-> !set.contains(i))
               .forEach(e-> System.out.println(e));

       //alternate
        String s3 = s + t;
        System.out.println(s3);
        StringBuffer sb = new StringBuffer();
        Map<String, Long> map =Arrays.stream(s3.split(""))
                .collect(Collectors.groupingBy(y -> y, Collectors.counting()));
        map.entrySet().stream()
                .filter(o -> o.getValue() == 1)
                .map(o -> o.getKey())
                .forEach(e -> sb.append(e));

        System.out.println("extra string  " + sb);

       //alternate

        char[] ch = s.toCharArray();
        char[] c = t.toCharArray();
        char result = 0;

        for (int i = 0; i < ch.length; i++) {
            result ^= ch[i];
        }

        for (int i = 0; i < c.length; i++) {
            result ^= c[i];
        }

        System.out.println(result);

    }
}
